lsi: false
safe: true
ignore_theme_config: true
timezone: "Europe/Berlin"
encoding: utf-8
strict_front_matter: true
keep_files: [.gitkeep]
markdown: kramdown
exclude: [CHANGELOG.md, Makefile, .idea/workspace.xml]
plugins:
  - jemoji
  - jekyll-paginate