title: "MPOWR IT GmbH i.G."
url: "https://mpowr.it"
baseurl: ""
description: > # this means to ignore newlines until "email:"
  WE EMPOWER YOUR IT DEPARTMENT

logo: "/assets/images/logo_m.webp"
float_logo: true
cover: "/assets/images/header.webp"
paginate: 5