url: "https://mpowr.it"
baseurl: ""
title: "MPOWR IT GmbH"
description: > # this means to ignore newlines until "email:"
  Wir helfen deinem IT Team den Fokus auf wertschöpfnde Arbeit zu finden.

logo: "/assets/images/mpowr-logo-links-farbig.svg"
cover: "/assets/images/header.webp"
paginate: 5