url: "https://mpowr.it"
baseurl: ""
description: > # this means to ignore newlines until "email:"
  WE EMPOWER YOUR IT DEPARTMENT

logo: "/assets/images/mpowr-logo-links-farbig.svg"
cover: "/assets/images/header.webp"
paginate: 5