url: "https://mpowr.it"
baseurl: ""
title: "MPOWR IT GmbH"
description: > # this means to ignore newlines until "email:"
  Unterstützung deines IT-Teams bei der Fokussierung auf wertschöpfende Tätigkeiten.

logo: "/assets/images/mpowr-logo-links-farbig.svg"
cover: "/assets/images/header.webp"
paginate: 5
