url: "https://mpowr.it"
baseurl: ""
title: "MPOWR IT GmbH"
description: > # this means to ignore newlines until "email:"
  Wir unterstützen Deine IT-Teams bei der Fokussierung auf wertschöpfende Aufgaben und bringen so Dein Unternehmen voran.

logo: "/assets/images/mpowr-logo-links-farbig.svg"
cover: "/assets/images/header.webp"
paginate: 5
